# Generated by Django 3.2.12 on 2023-07-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/images/blogCover')),
                ('bookUrl', models.URLField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
