# Generated by Django 3.2.12 on 2023-07-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20230711_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='level',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
